SET PASSWORD FOR '$MARIADB_ROOT_USER'@'$MARIADB_DATABASE_HOST' = PASSWORD('$MARIADB_ROOT_PASSWORD');
CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;
CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';
GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
