SET PASSWORD FOR 'root'@'localhost' = PASSWORD('1234');
CREATE DATABASE IF NOT EXISTS `wp_db`;
CREATE USER 'seungsle'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON `wp_db`.* TO 'seungsle'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
